### PR TITLE
Structured

### PR DESCRIPTION
**Pull request by PabloMosUU**
This creates structured annotations from the beginning, and no string manipulations are done. Before merging, I need to test it on some real data (which I have access to). Also, some to-do items for the future:
- remove deduce.has_nested_tags and utilcls.AbstractSpan.is_nested
- rewrite deduce.deidentify_annotations using structured annotations
- reuse deduce.merge_adjacent_tags in utility.flatten_text

### CODE REVIEW

**Comment by PabloMosUU** [comment]
I also need to make it compatible with Python 3.7 and Python 3.8

**Comment by PabloMosUU** [comment]
At this point, I will stop working on this branch until at least January. These are the items that are left to be completed:

- [ ] Test on real data to see if any errors arise
- [ ] Compare the results with those of the next-release branch, to ensure that no annotations are different from before
- [ ] Check the memory and time efficiency of this code as compared to the next-release branch (if memory is a concern, try removing the text from the spans)
- [ ] See other "todo" items listed in my previous comment and in the code

**Comment by PabloMosUU** [comment]
I've finished testing the code extensively to make sure that it matches the previous behaviour. I've generated a report that I will send to you separately.

**Comment by vmenger** [comment]
For future reference (mainly intended for myself):

Just ran on a sample of 1000 documents from different sources. It threw:

42x AnnotationError "The spans corresponding to the match belong to annotations"
2x IndexError "list index out of range"

Some minimal examples to reproduce some errors: 

```
    annotate_text("dr. Fransen, Postbus 34858")
    annotate_text("A", "Albert")
    annotate_text("23/3 8.4")
    annotate_text("0030857428347")
    annotate_text("8888888888888888888888")
```

Another point of attention is that the time it took to annotate was 364 seconds vs 233 seconds, (+56%).

For the rest code and tests look good, and the annotation seems more or less identical (or slightly improved), which is also nice. This needs just a little more work before it's safe to release I would say, hope to pick it up in the near future.

**Comment by PabloMosUU** [comment]
I just looked into fixing the merge conflicts with respect to next-release, but I see that they stem from some fundamental changes in the code structure. Furthermore, it looks like all of this has already been implemented in next-release. Does that mean that this pull request is obsolete?

**Comment by vmenger** [comment]
Hi Pablo,

I'm hoping that the latest release, 2.0.0 does everything that was in this branch. I'm still very grateful for showing that it was possible, but in the end I decided on a bit of a different approach that I think will enable more future improvements. So I think we can close this PR now, but let me know if you have any comments/other thoughts.

**Comment by PabloMosUU** [comment]
:( but :)

**Pull request closed without merging**
