### PR TITLE
add new version

### PR DESCRIPTION
**Pull request by PabloMosUU**

### CODE REVIEW

**Comment by PabloMosUU** [comment]
I tried to do this directly on next-release, but because it is a protected branch, I can't

**Comment by PabloMosUU** [comment]
After merging this pull request, we can merge next-release to master and push to pypi. But I think you'll have to do it, because next-release is a protected branch and I don't have access

**Review by vmenger — APPROVED** [review]

**Comment by vmenger** [comment]
Thanks for solving all the conflicts! Everything should be good now in next-release?

**Comment by PabloMosUU** [comment]
I've created the pull request to merge next-release into master. However, there are conflicts, and I can't resolve them because I'm not allowed to push to next-release

**Pull request merged**
